package net.miatech.praxis.flown.dto;

import lombok.Data;

/**
 *
 * @author dvicente
 */
@Data
public class A4622 {
    private String CCUST,CCIA,FORMA,SERIE,CUPON,SEQVTA,SEQ,STVAL,FTE,GRUPO,FPROC,CDOC,
            TDOC,PSVVTA,AGTIA,FVTA,TPAX,CARR,CARROP,VCPN,COMISI,SCOMISI,YQ,MDACP,VCPNRV,
            COMREV,SCOMREV,YQREV,TUSO,DFLIGHT,NFLIGHT,CDEPART,CARRIVA,LOTE,STCHG,USCR,FECR,HOCR,USUP,FEUP,HOUP,
            STUSE,RFIC,RFIS;
}
