
Ext.define('Ext.Praxis.model.salesAudit.GridData', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'A2537CCUST',  type: 'string'},
        {name: 'A2537SEQ',    type: 'string'},
        {name: 'A2537NCASO',  type: 'string'},
        {name: 'A2537PCASO',  type: 'string'},
        {name: 'A2537FCRRE',  type: 'string'},
        {name: 'A2537HCRRE',  type: 'string'},
        {name: 'A2537FVETO',  type: 'string'},
        {name: 'A2537HVETO',  type: 'string'},
        {name: 'A2537ESTAD',  type: 'string'},
        {name: 'A2537CODIT',  type: 'string'},
        {name: 'A2537PNR',    type: 'string'},
        {name: 'A2537NVLO',   type: 'string'},
        {name: 'A2537FVLO',   type: 'string'},
        {name: 'A2537HVLO',   type: 'string'},
        {name: 'A2537ITIN',   type: 'string'},
        {name: 'A2537NPAX',   type: 'string'},
        {name: 'A2537TKTS',   type: 'string'},
        {name: 'A2537TCASO',  type: 'string'},
        {name: 'A2537CCPTO',  type: 'string'},
        {name: 'A2537SCPTO',  type: 'string'},
        {name: 'A2537CURRW',  type: 'string'},
        {name: 'A2537AMOUW',  type: 'string'},
        {name: 'A2537IATAE',  type: 'string'},
        {name: 'A2537AGENE',  type: 'string'},
        {name: 'A2537EJECB',  type: 'string'},
        {name: 'A2537DESCR',  type: 'string'},
        {name: 'A2537RUTAA',  type: 'string'},
        {name: 'A2537INGRE',  type: 'string'},
        {name: 'A2537FINGR',  type: 'string'},
        {name: 'A2537HINGR',  type: 'string'},
        {name: 'A2537MODIF',  type: 'string'},
        {name: 'A2537FMODI',           type: 'string'},
        {name: 'A2537HMODI',           type: 'string'},
        {name: 'A2537TKTS_HAS_WAIVER', type: 'string'}
    ]
});
