package net.miatech.praxis.payment.filter;

import lombok.Data;

/**
 *
 * @author Dvicente
 */
@Data
public class A4331SRFilter {
    private String PRDA,PAYDATE,FEUP,DESC_PROCTYPE,
            A4501FECVT,A4496FPROC,A4501FEUP;
    private Integer TOTAL,
            TOTAL_MATCH,TOTAL_PENDING,
            TOTAL_NC_MATCH,TOTAL_NC_PENDING,
            TOTAL_PG_MATCH,TOTAL_PG_PENDING,
            TOTAL_LIG_MATCH,TOTAL_LIG_PENDING,
            TOTAL_TAB_MATCH,TOTAL_TAB_PENDING;
   
    // New Fields
    private Integer TOTAL_AX,TOTAL_VI_MC,TOTAL_DC,TOTAL_TP,TOTAL_BO,TOTAL_OTHER,TOTAL_CA,
            TOTAL_MATCH_AX,TOTAL_MATCH_VI_MC,TOTAL_MATCH_DC,TOTAL_MATCH_TP,TOTAL_MATCH_BO,TOTAL_MATCH_OTHER,TOTAL_MATCH_CA,
            TOTAL_PENDING_AX,TOTAL_PENDING_VI_MC,TOTAL_PENDING_DC,TOTAL_PENDING_TP,TOTAL_PENDING_BO,TOTAL_PENDING_OTHER,TOTAL_PENDING_CA,
            TOTAL_BY_PAYMENT;

}
